- access_groups: ''
  creator: admin
  description: ''
  labels:
    212d3ff2-9a22-4232-bcf1-b99c09ed91d6:
      alignment: left
      content: "This site contains:\r\n- top-level nodes of type \"Device\" and \"\
        Router\"\r\n- top-level links of type \"Link\" and \"Ethernet Link\""
      positions: [-216, 184]
  last_modified: '2021-12-21 12:22:12.803733'
  links: ['[Site 1: Top Level Shared and Non Shared Objects] R1 - R2', R1 - R3, R2
      - R3]
  location: ''
  model: ''
  name: 'Site 1: Top Level Shared and Non Shared Objects'
  nodes: ['[Site 1: Top Level Shared and Non Shared Objects] Router 1', '[Site 1:
      Top Level Shared and Non Shared Objects] Router 2', Router 3]
  positions: {}
  scoped_name: 'Site 1: Top Level Shared and Non Shared Objects'
  shared: false
  sites: []
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  labels: {}
  last_modified: '2021-12-16 04:03:11.512797'
  links: []
  location: ''
  model: ''
  name: 'Site 2: Subsites'
  nodes: []
  positions: {}
  scoped_name: 'Site 2: Subsites'
  shared: false
  sites: []
  subtype: ''
  type: site
  vendor: ''
