- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    22ddf544-3151-4361-940b-7516b78c179a:
      alignment: left
      content: "Basic site with three devices: Router 1 is of type \"device\" and\
        \ the other two are \"router\".\r\nAll three links are Ethernet links.\r\n\
        Router 1 should be displayed as a router, Router 2 as a host and Router 3\
        \ as an optical switch.\r\nThe icon of a device is decoupled from its type."
      positions: [19, -70]
  last_modified: '2022-01-01 11:49:31.237079'
  latitude: '0.0'
  links: [R1 - R2, R2 - R3, R1 - R3]
  location: ''
  longitude: '1.0'
  model: ''
  name: 'Site 1: Top-level Devices and Links'
  nodes: [Router 1, Router 2, Router 3]
  pools: [Everything, All Sites]
  positions: {}
  sites: []
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    ebac22df-1242-4dcd-90b0-fbeeee517991:
      alignment: left
      content: "- Enter subsite 1 and subsite 2 and make sure all of them have the\
        \ expected content.\r\n- Test the backward, forward and upward navigation\
        \ buttons.\r\n- Test the Site Tree to select any node, including a node that\
        \ is in a different site:\r\nthe view should immediately switch to the site\
        \ of the selected node.\r\n- Test using site as a teleport: Subsite 1 contains\
        \ Subsite 2 and vice-versa,\r\nto switch from one to the other and back."
      positions: [-310, -212]
  last_modified: '2022-01-04 01:44:52.125534'
  latitude: '0.0'
  links: []
  location: ''
  longitude: '0.0'
  model: ''
  name: 'Site 2: Subsite and Teleport Mechanism'
  nodes: [Subsite 2, Subsite 1]
  pools: [Everything, All Sites]
  positions: {}
  sites: []
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    6eb6d97f-31c8-4a2a-8142-8c1427cea64d:
      alignment: left
      content: "This subsite should contain\r\n- three routers, \"Subsite 1 - R1-3\"\
        \r\n- three links between each pair of routers, \"Subsite 1 - L1-3\""
      positions: [51, -231]
  last_modified: '2022-01-03 12:55:19.074280'
  latitude: '0.0'
  links: [Subsite 1 - L1, Subsite 1 - L2, Subsite 1 - L3]
  location: ''
  longitude: '0.0'
  model: ''
  name: Subsite 1
  nodes: [Subsite 2, Subsite 1 - R1, Subsite 1 - R2, Subsite 1 - R3]
  pools: [Everything, All Sites]
  positions:
    'Site 2: Subsite': &id001 [-558, -27]
    'Site 2: Subsite and Teleport Mechanism': *id001
    Subsite 2: [-15, 43]
  sites: [Subsite 2, 'Site 2: Subsite and Teleport Mechanism']
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    6bc3e996-eb39-4d52-9294-15cdd7d10f92:
      alignment: left
      content: "Tests the creation, editing and deletion of sites and the nodes inside\
        \ it.\r\n- Create three devices: 1 Device, 1 Router and 1 Gateway. The default\
        \ icon for the Device and Router should be a router,\r\nbut it should a host\
        \ (computer) for the Gateway.\r\n- Create links between them, including Ethernet\
        \ Link and Link.\r\n- Edit the name of a node and the name of a link: the\
        \ name must be instantly\r\nupdated.\r\n- Edit the name of the site and refresh:\
        \ check that the positions are the same (the \"update\" position of the Site\
        \ class is replacing old with new positions).\r\n- Delete a device: check\
        \ that the two connected links are also deleted from the site.\r\nCheck that\
        \ these objects still exist in the inventory: deleting from a site should\
        \ not delete the original objects.\r\n- Use the right-click multiple selection\
        \ rectangle to delete the remaining objects.\r\n- Delete the site itself from\
        \ the Site table."
      positions: [227, -507]
  last_modified: '2022-01-01 10:33:29.627883'
  latitude: '0.0'
  links: []
  location: ''
  longitude: '0.0'
  model: ''
  name: 'Site 3: Creation, Edit and Deletion'
  nodes: []
  pools: [All Sites, Everything]
  positions: {}
  sites: []
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    56c77f3e-481c-476d-a045-1120b3cb0cc2:
      alignment: left
      content: "This subsite should contain\r\n- two gateways, \"Subsite 2 - G1-2\"\
        \r\n- one link between them, \"Subsite 2 - L1\""
      positions: [4, -181]
  last_modified: '2022-01-03 12:55:37.570662'
  latitude: '0.0'
  links: [Subsite 2 - L1]
  location: ''
  longitude: '0.0'
  model: ''
  name: Subsite 2
  nodes: [Subsite 1, Subsite 2 - G1, Subsite 2 - G2]
  pools: [Everything, All Sites]
  positions:
    'Site 2: Subsite': &id002 [-144, -36]
    'Site 2: Subsite and Teleport Mechanism': *id002
    Subsite 1: [-2, -48]
  sites: [Subsite 1, 'Site 2: Subsite and Teleport Mechanism']
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    0a8dc15c-8f31-4fe2-b84d-1b2e9680876e:
      alignment: left
      content: "Tests the duplication of devices, subsites and top-level sites.\r\n\
        - Duplicate \"Duplicate me 1\": the duplicated device should be immediately\
        \ added to the site.\r\nRefresh and check that it is still displayed at the\
        \ same position.\r\n- Duplicate \"Duplicate me 2\": the duplicate subsite\
        \ should be immediately added to the site.\r\nDouble-click on it to check\
        \ that the content is the same as \"Duplicate me 2\".\r\n- Create a link between\
        \ the two devices.\r\n- Duplicate the top-level site: check that it contains\
        \ the two devices and the link between them,\r\nas well as the two subsites,\r\
        \nCheck that the content of the subsites is the same as that of the original\
        \ top-level site."
      positions: [-47, -187]
  last_modified: '2022-01-02 02:48:13.708604'
  latitude: '0.0'
  links: [Duplicate 1 - 2]
  location: ''
  longitude: '0.0'
  model: ''
  name: 'Site 4: Duplication of Devices, Subsites and Top-level Sites'
  nodes: [Duplicate me 2, Duplicate me 1]
  pools: [All Sites, Everything]
  positions: {}
  sites: []
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels: {}
  last_modified: '2022-01-01 11:55:14.172281'
  latitude: '0.0'
  links: [G1 - R1]
  location: ''
  longitude: '0.0'
  model: ''
  name: Duplicate me 2
  nodes: [Duplication - G1, Duplication - R1]
  pools: [All Sites, Everything]
  positions:
    'Site 4: Duplication of Devices, Subsites and Top-level Sites': [135, 6]
  sites: ['Site 4: Duplication of Devices, Subsites and Top-level Sites']
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    65702104-28b9-4392-9472-727f6f3bf273:
      alignment: left
      content: "Tests the display of loopback and parallel links:\r\n- One loopback\
        \ link for each device.\r\n- Odd number (3) of same direction links between\
        \ R1 and R2\r\n- Even number (4) of different direction links (3 / 1) between\
        \ R1 and R3\r\n- Odd number (3) of different direction links (2 / 1) between\
        \ R2 and R4\r\n- Even number (8) of different direction links (4 / 4) between\
        \ R3 and R4\r\n- One link between R1 and R4"
      positions: [-499, 98]
  last_modified: '2022-01-02 12:41:17.767672'
  latitude: '0.0'
  links: [R3 -> R2 L1, R3 -> R2 L2, R3 -> R2 L3, R3 -> R2 L4, R3 Loopback 1, R1 Loopback
      1, R1 -> R2 L1, R1 -> R2 L2, R1 -> R2 L3, R1 -> R3 L1, R3 -> R1 L2, R3 -> R1
      L3, R3 -> R1 L4, R2 -> R4 L1, R2 -> R4 L2, R4 -> R2 L3, R4 Loopback 1, R1 -
      R4, R3 -> R4 L1, R3 -> R4 L2, R3 -> R4 L3, R3 -> R4 L4, R4 -> R3 L5, R4 -> R3
      L6, R4 -> R3 L7, R4 -> R3 L8]
  location: ''
  longitude: '0.0'
  model: ''
  name: 'Site 5: Loopback and Parallel Links'
  nodes: [S5 R1, S5 R2, S5 R3, S5 R4]
  pools: [Everything, All Sites]
  positions: {}
  sites: []
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    df3da1e5-33a3-46e4-baed-ee59a432c773:
      alignment: left
      content: "Tests multiple levels of nested subsites, in particular:\r\n- The\
        \ upward navigation button\r\n- The Tree View to switch between levels\r\n\
        - The Duplication: all subsites down to the last should be duplicated."
      positions: [40, -173]
  last_modified: '2022-01-03 03:26:54.919735'
  latitude: '0.0'
  links: []
  location: ''
  longitude: '0.0'
  model: ''
  name: 'Site 6: Subsubsite and Subsubsubsite'
  nodes: [L1 Site]
  pools: [Everything, All Sites]
  positions: {}
  sites: []
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels: {}
  last_modified: '2022-01-02 12:46:03.753457'
  latitude: '0.0'
  links: []
  location: ''
  longitude: '0.0'
  model: ''
  name: L1 Site
  nodes: [L2 Site]
  pools: [Everything, All Sites]
  positions:
    'Site 6: Subsubsite and Subsubsubsite': [-27, -55]
  sites: ['Site 6: Subsubsite and Subsubsubsite']
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels: {}
  last_modified: '2022-01-02 12:46:14.439473'
  latitude: '0.0'
  links: []
  location: ''
  longitude: '0.0'
  model: ''
  name: L2 Site
  nodes: [L3 Site]
  pools: [Everything, All Sites]
  positions: {}
  sites: [L1 Site]
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels: {}
  last_modified: '2022-01-02 12:47:02.746851'
  latitude: '0.0'
  links: [S6 L1]
  location: ''
  longitude: '0.0'
  model: ''
  name: L3 Site
  nodes: [S6 L3 R1, S6 L3 R2]
  pools: [Everything, All Sites]
  positions: {}
  sites: [L2 Site]
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    40db70f9-22d1-4497-8834-52ef5b1bf369:
      alignment: left
      content: "- Import the pool \"All routers in Europe\" with the option \"Add\
        \ connected links\"\r\n- Click on the \"Automatic Layout\" button: the network\
        \ should be displayed in a near-optimal layout almost instantly.\r\n- Select\
        \ everything and delete it."
      positions: [63, -168]
  last_modified: '2022-01-04 01:46:34.380620'
  latitude: '0.0'
  links: []
  location: ''
  longitude: '0.0'
  model: ''
  name: 'Site 7: Automatic Layout of Large Graph'
  nodes: []
  pools: [Everything, All Sites]
  positions: {}
  sites: []
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  icon: site
  labels:
    9d96833e-cf92-45e4-8c54-f2b145b5e542:
      alignment: left
      content: "- Add nodes \"Dallas\" and \"Atlanta\" without option: the nodes should\
        \ be added without any links.\r\n- Delete them\r\n- Add \"Washington\" and\
        \ \"Austin\" with the \"Add Connected Links\" option: no link should be created.\r\
        \n- Add \"Dallas\" and \"Atlanta\" with the \"Add Connected Links\" option:\r\
        \nit should create one link between \"Washington\" and \"Atlanta\" (link16),\r\
        \none link between \"Dallas\" and \"Austin\" (link13),\r\nand three links\
        \ between \"Dallas\" and \"Atlanta\" (link25, 25-2 and 25-3)\r\n- Add \"Dallas-2\"\
        \ with the \"Add Connected Links\" option:\r\nit should add \"Dallas-2\" along\
        \ with two links:\r\n\"link25-reversed\" and \"link25-dallas2\"\r\n- Delete\
        \ everything\r\n- Add \"link25\" with no option: nothing should be added (missing\
        \ end nodes).\r\n- Add \"link25\" with the \"Add Connected Nodes\" option:\
        \ \"Dallas\" and \"Atlanta\" should be added along with \"link25\".\r\n- Add\
        \ \"link25-2\" with the \"Add Connected Nodes\" option: the link should be\
        \ added but the two ends are already here.\r\n- Add \"link25-3\" without any\
        \ option: the link should be added between \"Dallas\" and \"Atlanta\"."
      positions: [110, -18]
  last_modified: '2022-01-04 02:21:05.036701'
  latitude: '0.0'
  links: []
  location: ''
  longitude: '0.0'
  model: ''
  name: 'Site 8: Import with Add Connected Nodes and Links'
  nodes: []
  pools: [All Sites, Everything]
  positions: {}
  sites: []
  subtype: ''
  type: site
  vendor: ''
