- access_groups: ''
  creator: admin
  description: ''
  labels: {}
  last_modified: '2021-12-16 04:03:03.882382'
  links: ['[Site 1: Top Level Objects] R1 - R2']
  location: ''
  model: ''
  name: 'Site 1: Top Level Objects'
  nodes: ['[Site 1: Top Level Objects] Router 1', '[Site 1: Top Level Objects] Router
      2']
  positions: {}
  scoped_name: 'Site 1: Top Level Objects'
  shared: false
  sites: []
  subtype: ''
  type: site
  vendor: ''
- access_groups: ''
  creator: admin
  description: ''
  labels: {}
  last_modified: '2021-12-16 04:03:11.512797'
  links: []
  location: ''
  model: ''
  name: 'Site 2: Subsites'
  nodes: []
  positions: {}
  scoped_name: 'Site 2: Subsites'
  shared: false
  sites: []
  subtype: ''
  type: site
  vendor: ''
